# Generated by Django 2.2.14 on 2020-11-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estatus', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('creditos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ListaClases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clases.Clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='clases',
            field=models.ManyToManyField(related_name='clase', through='estudiantes.ListaClases', to='clases.Clase'),
        ),
    ]
